### ISSUE TITLE
Speed compared to IP-Adapter FaceID

### ISSUE THREAD

**Issue by linhqyy** [JackAILab/ConsistentID#24]
Hi, I recently conducted an experiment comparing the speed of IP-Adapter FaceID and ConsistentID. Interestingly, I noticed that ConsistentID seemed to have a faster forward process compared to IP-Adapter FaceID. I was wondering if you could provide some insights into why this might be the case. I'm curious to understand the factors that contribute to the difference in speed between the two approaches. Any explanations or thoughts you could share would be greatly appreciated!

**Comment by JackAILab** [comment]
Thank you for your attention. In fact, there is not much theoretical difference in the inference speed between our model and the IPAdapter-FaceID version. The speed difference may be due to graphics card version, additional model loading, or adjustments to the amount of model parameters. Can you provide more detailed information in these aspects to facilitate further inspection?

If you want faster speedup, you can also replace the base mode with an LCM model, or use a faster GPU (such as A100) for inference.

**Comment by linhqyy** [comment]
@JackAILab  After trying again, I noticed that the first forward process of  IP Adapter appears to be slower compared to ConsistentID's initial forward pass. However, it seems that after the first prompt, the speed of the two becomes quite similar. Do you have any idea about this phenomenon?

**Comment by linhqyy** [comment]
Btw, I used A100 for inference :))

**Comment by ifredom** [comment]
Is it different from facefusion? facefusion can use the cpu
