### ISSUE TITLE
background_loss

### ISSUE THREAD

**Issue by gaoyixuan111** [JackAILab/ConsistentID#40]
In the project code, the background loss is computed using `parsing_mask_lists`, but the final loss consists of the prediction loss and facial loss added together. Why isn't it the sum of all three losses? What is the purpose of setting the `background_loss`?

**Comment by JackAILab** [comment]
Hi, @gaoyixuan111 , background_loss is designed to prevent background from interfering with text instructions during training. It is actually another form of predict_loss (but the background is removed). The only losses used are facial_loss and predict_loss ([Line 270](https://github.com/JackAILab/ConsistentID/blob/main/train.py#L270)). Background loss is for debugging convenience and is not actually used.
We explained in the Experimental Implements section of the paper that the model removes background information with a probability of 50%.

**Comment by JackAILab** [comment]
@gaoyixuan111 hi, In some cases, llava will generate too long descriptions. In actual testing, only a small percentage of facial captions are generated, so you can consider discarding this part of facial captions directly.

We have updated the utils.py [Line102](https://github.com/JackAILab/ConsistentID/blob/main/utils.py#L102) file to prevent errors caused by too long facial text.

**Comment by JackAILab** [comment]
@gaoyixuan111 Just ignore the indexing errors warning, which is mainly caused by the position of the trigger word. Running according to the current code logic will not actually cause this error.

In addition, you should use max_text_length > 300. Too small max_text_length will cause the text to be item["vqa_llva"] in most cases. Such text cannot substitute facial features images into text embedding.

**Comment by gaoyixuan111** [comment]
@JackAILab 
I printed the network parameter count for `facial_encoder`. Could you share the training duration and device information for training `facial_encoder?
`facial_encoder` contains: 105.772288 million parameters."
